#!/usr/bin/python3

# Import modules for CGI handling 
import cgi, cgitb 
import mosquitto
import os
import time
 
broker = "127.0.0.1"
port = 1883
 
mypid = os.getpid()
client_uniq = "pubclient_"+str(mypid)
mqttc = mosquitto.Mosquitto(client_uniq)
 
#connect to broker
mqttc.connect(broker, port, 60, True)

# Create instance of FieldStorage 
form = cgi.FieldStorage() 

# Get data from fields
cgi_colour = form.getvalue('colour')

print ("Content-type:text/html\r\n\r\n")
print ("<html>")
print ("<head>")
print ("<title>Python3 CGI Program</title>")
print ("</head>")
print ("<body>")
print ("<h2>Message sent to MQTT</h2>")
 
mqttc.publish("test/pi/colour", cgi_colour)

print ("<p>Message published: "+cgi_colour)
print ("</body>")
print ("</html>")
